/**
 * Represents a physical room or outdoor area where plants are located.
 */
export interface Room {
  id: string; // UUID or similar unique identifier
  name: string;
  lightDirection: 'North' | 'East' | 'South' | 'West';
  indoor: boolean;
}

/**
 * Represents a plant managed by the application.
 */
export interface Plant {
  id: string; // UUID or similar unique identifier
  roomId: string; // Foreign key referencing Room.id
  name: string;
  windowDistanceCm?: number;
  nearHeater?: boolean;
  sizeCm?: number;
  potSizeCm?: number;
}

/**
 * Represents an image associated with a plant.
 */
export interface PlantImage {
  id: string; // UUID or similar unique identifier
  plantId: string; // Foreign key referencing Plant.id
  timestamp: number; // Unix timestamp (ms)
  dataURL: string; // base64 encoded image data
}

/**
 * Represents a task related to plant care.
 */
export interface Task {
  id: string; // UUID or similar unique identifier
  plantId: string; // Foreign key referencing Plant.id
  type: 'Watering' | 'Fertilizing' | 'Repotting' | 'Cleaning' | 'Photo';
  dueDate: number; // Unix timestamp (ms)
  done: boolean;
  notes?: string; // Optional notes for the task
}

/**
 * Represents care tips, potentially generated by OpenAI.
 */
export interface Tip {
  id: string; // UUID or similar unique identifier
  plantId: string; // Foreign key referencing Plant.id
  generatedAt: number; // Unix timestamp (ms)
  content: string; // The actual tip content
}
/**
 * Application settings, stored under a fixed key.
 */
export interface Settings {
  /**
   * OpenAI API key provided by the user.
   */
  openAiApiKey: string;
}
